 set tv ntsc
 set romsize 4k

 rem **************************************************************************
 rem Options
 rem **************************************************************************

 

 rem **************************************************************************
 rem Setup: 
 rem - set initial values
 rem **************************************************************************
 COLUBK = $0F
 score = 00000 :  scorecolor = $08

 const true = 1
 const false = 0

 dim player0frame = x
 dim player1frame = z
 dim newbackground = y
 dim loopcounter = w
 dim channnel0duration = v
 dim channnel1duration = u
 dim player0size = t
 dim player1size = s
 dim player0realcolor = r
 dim player1realcolor = q
 dim player0animation = p
 dim player1animation = o
 dim framecounter = n

 newbackground = 1

 player0x = 75 : player0y = 75
 player1x = 75 : player1y = 25
 ballx = 0 : bally = 0

 player1realcolor = $80
 player0realcolor = $40
 player1size = $30
 player0size = $30
 COLUBK = $C4
 COLUPF = $0E
 player0animation = 1

  rem **************************************************************************
  rem Event: system_start.
  rem **************************************************************************
system_start_begin

system_start_end

fullgameloop

  rem **************************************************************************
  rem Event: title_start.
  rem **************************************************************************
title_start_begin
  newbackground = 1
  player0y = 0
  player1y = 0
title_start_end

  rem **************************************************************************
  rem Event: title_update.
  rem **************************************************************************
title_update_begin
  gosub commongamelogic
  drawscreen
  if joy0fire then goto _if_1 else goto _if_1_end
_if_1
  goto gameplay_start_begin
_if_1_end
  goto title_update_begin
title_update_end

  rem **************************************************************************
  rem Event: gameplay_start.
  rem **************************************************************************
gameplay_start_begin
  newbackground = 2
  player0y = 80
  player1y = 20
gameplay_start_end

 rem **************************************************************************
 rem Main loop: 
 rem **************************************************************************
main

 gosub commongamelogic
 drawscreen

 rem **************************************************************************
 rem Code generated by vcs-game-maker.
 rem **************************************************************************





  if joy0down then goto _if_2 else goto _if_2_end
_if_2
  if joy0fire then goto _if_3 else goto _if_3_end
_if_3
  pfscroll upup
  goto _if_3_else_end
_if_3_end

  pfscroll up

_if_3_else_end
_if_2_end

  if joy0up then goto _if_4 else goto _if_4_end
_if_4
  if joy0fire then goto _if_5 else goto _if_5_end
_if_5
  pfscroll downdown
  goto _if_5_else_end
_if_5_end

  pfscroll down

_if_5_else_end
_if_4_end
  

 rem **************************************************************************
 rem End of generated code.
 rem **************************************************************************

 goto main
 
  rem **************************************************************************
  rem Event: gameover_start.
  rem **************************************************************************
gameover_start_begin

gameover_start_end

  rem **************************************************************************
  rem Event: gameover_update.
  rem **************************************************************************
gameover_update_begin

gameover_update_end

 goto fullgameloop

 rem **************************************************************************
 rem Common game logic subroutine.
 rem **************************************************************************

commongamelogic

 framecounter = framecounter + 1

 rem **************************************************************************
 rem Sound handling.
 rem **************************************************************************

 if channnel0duration = 1 then AUDV0 = 0
 if channnel0duration <> 0 then channnel0duration = channnel0duration - 1

 if channnel1duration = 1 then AUDV1 = 0
 if channnel1duration <> 0 then channnel1duration = channnel1duration - 1


 rem **************************************************************************
 rem - Draws the screen and handles user input. Moves the sprites and
 rem - the ball's position and handles collisions
 rem **************************************************************************
 COLUP1 = player1realcolor
 COLUP0 = player0realcolor
 NUSIZ0 = player0size
 NUSIZ1 = player1size
 if player0size{3} then REFP0 = 8 else REFP0 = 0
 if player1size{3} then REFP1 = 8 else REFP1 = 0

 rem **************************************************************************
 rem Backgrounds generated by vcs-game-maker.
 rem **************************************************************************

 if newbackground = 0 then goto backgroundchangeend
 if newbackground <> 1 then goto background1end
 playfield:
  ................................
  ..XXX...X..........XX...X.......
  ..X..X..X.........X....XXX..XX..
  ..X.X...X...XX.....XX...X..X..X.
  ..X..X..X..X..X......X..X..X..X.
  ..XXX...X...XX.X...XX...X...XX..
  ................................
  ................................
  ................................
  ................................
  ................................
end
background1end

 if newbackground <> 2 then goto background2end
 playfield:
  X.............................X.
  X.............................X.
  X.............................X.
  X.............................X.
  X.............................X.
  X.............................X.
  X.............................X.
  X.............................X.
  X.............................X.
  X.............................X.
  X.............................X.
end
background2end
backgroundchangeend
 newbackground = 0

 rem **************************************************************************
 rem Animations generated by vcs-game-maker.
 rem **************************************************************************

   rem Animations for player0:

  if player0frame <> 255 then goto player0animationsStart
  player0:
  %00000000
end
  goto player0animationsEnd

player0animationsStart

player0animation0Start

  rem Animation 0 Example1 for player0:

  player0frame = player0frame + 1
  if player0frame >= 20 then player0frame = 0

  if player0frame > 10 then goto player0animation0frame0End
  player0:
  %00100010
  %00010100
  %00001010
  %00111110
  %00101000
  %00011100
  %00011100
  %00011100
end
  goto player0animation0animationEnd
player0animation0frame0End

  if player0frame > 20 then goto player0animation0frame1End
  player0:
  %00010100
  %00010100
  %00101000
  %00111110
  %00001010
  %00011100
  %00011100
  %00011100
end
  goto player0animation0animationEnd
player0animation0frame1End

player0animation0animationEnd
  goto player0animationsEnd

player0animationsEnd


  rem Animations for player1:

  if player1frame <> 255 then goto player1animationsStart
  player1:
  %00000000
end
  goto player1animationsEnd

player1animationsStart

player1animation0Start

  rem Animation 0 Example1 for player1:

  player1frame = player1frame + 1
  if player1frame >= 20 then player1frame = 0

  if player1frame > 10 then goto player1animation0frame0End
  player1:
  %00100010
  %00010100
  %00001010
  %00111110
  %00101000
  %00011100
  %00011100
  %00011100
end
  goto player1animation0animationEnd
player1animation0frame0End

  if player1frame > 20 then goto player1animation0frame1End
  player1:
  %00010100
  %00010100
  %00101000
  %00111110
  %00001010
  %00011100
  %00011100
  %00011100
end
  goto player1animation0animationEnd
player1animation0frame1End

player1animation0animationEnd
  goto player1animationsEnd

player1animationsEnd

 return
